name: AsbestosHazard
main: uk.co.xfour.asbestoshazard.AsbestosHazardPlugin
version: 1.2.1
api-version: 1.19
authors:
  - Codex
commands:
  asbestoschunk:
    description: Check whether your current chunk is within the asbestos zone.
    usage: /<command>
