name: Transport
version: ${project.version}
main: uk.co.xfour.transport.TransportPlugin
api-version: '1.21'
author: xfour
website: https://github.com/xfour/Minecraft-Plugins
description: Vehicle systems for trains, planes, cars, rail networks, and spaceships.
commands:
  transport:
    description: Manage the Transport plugin modules.
    usage: /<command> <status|reload|give>
