name: KimJongUn2
main: uk.co.xfour.kimjongun2.KimJongUn2Plugin
version: 1.0.0
api-version: "1.20"
permissions:
  kimjongun2.admin:
    description: Allows admin commands for Kim Jong Un 2.
    default: op
  kimjongun2.spawn:
    description: Allows spawning Kim Jong Un 2 mobs.
    default: op
  kimjongun2.use:
    description: Allows using launchpads and missiles.
    default: true
