name: AsbestosHazard
main: com.example.asbestoshazard.AsbestosHazardPlugin
version: 1.0.0
api-version: 1.19
authors:
  - Codex
commands:
  asbestoschunk:
    description: Check whether your current chunk is within the asbestos zone.
    usage: /<command>
