name: SpaceTravel
version: ${project.version}
main: uk.co.xfour.spacetravel.SpaceTravelPlugin
api-version: '1.21'
author: xfour
website: https://github.com/xfour/Minecraft-Plugins
description: Interplanetary travel systems with launch pads, stations, and route planners.
