name: KimJongUnMob
main: uk.co.xfour.kimjongunmob.KimJongUnMobPlugin
version: 1.1.2
api-version: 1.19
dependencies:
  server:
    FancyNpcs:
      load: before
      required: true
      join-classpath: true
permissions:
  kimjongunmob.spawn:
    description: Allows spawning the Kim Jong Un mob.
    default: op
