name: KimJongUnMob
main: uk.co.xfour.kimjongunmob.KimJongUnMobPlugin
version: 1.1.2
api-version: 1.19
depend:
  - FancyNpcs
commands:
  spawnkim:
    description: Spawn the Kim Jong Un themed mob.
    usage: /spawnkim
    permission: kimjongunmob.spawn
permissions:
  kimjongunmob.spawn:
    description: Allows spawning the Kim Jong Un mob.
    default: op
