name: KimJongUn3
main: uk.co.xfour.kimjongun3.KimJongUn3Plugin
bootstrapper: uk.co.xfour.kimjongun3.KimJongUn3Bootstrap
version: 1.0.0
api-version: "1.21"
dependencies:
  server:
    Nova:
      required: true
      load: before
permissions:
  kimjongun3.admin:
    description: Allows admin commands for Kim Jong Un 3.
    default: op
  kimjongun3.use:
    description: Allows using launchpads and missiles.
    default: true
