name: KimJongUn
main: uk.co.xfour.kimjongun.KimJongUnPlugin
version: 1.0.0
api-version: "1.21"
permissions:
  kimjongun.admin:
    description: Allows admin commands for Kim Jong Un.
    default: op
  kimjongun.use:
    description: Allows using launchpads and missiles.
    default: true
