name: Furniture
version: ${project.version}
main: uk.co.xfour.furniture.FurniturePlugin
api-version: '1.21'
author: xfour
website: https://github.com/xfour/Minecraft-Plugins
description: Expansive furniture catalogue with modular decor packs.
commands:
  furniture:
    description: Manage the Furniture plugin modules.
    usage: /<command> <status|reload>
